### PR TITLE
Fixes for compilation with GCC 12/GCC 13

### PR DESCRIPTION
**Pull request by da-gazzi**
This PR includes a bunch of fixes that make it possible to compile the repo on non-Ubuntu 20.04 systems and/or with newer GCC versions (tested with GCC 12.2.0 on a heavily hacked CentOS 7.9 and GCC 13.2.1 on a stock Fedora 38 install _on a RISC-V based machine [MILK-V Pioneer])._ The following changes were made to fix general compilation issues:
- `#include` required C++ standard library headers (e.g., `cstdint`, `unordered_map`, ...) where needed
- replace use of `MAXFLOAT` with `std::numeric_limits<double>::max()`
- make sure log strings are formattable by:
  - `#include`-ing the correct headers in `logger.hpp`
  - `#include`-ing `logger.hpp` where needed
  - moving `ostream& operator<<` overloads into the appropriate namespaces for argument-dependent lookup to find them
The following changes were made to enable compilation on non-ARM/x86 machines:
- add a `NOFW` flag to the Makefile that disables firmware building (as done on ARM systems); this flag is enabled automatically on non-x86 systems
- replace Makefile guards checking for ARM systems with guards checking for non-x86 systems
- replace preprocessor guards checking for ARM systems with guards checking for non-x86 systems

The `umd` dependency also now points to a much more recent version with small fixes (separate PR on the respective repo). I don't know what the correct way is to deal with updated sub-dependencies in PRs.

### CODE REVIEW

**Comment by rjakovljevicTT** [comment]
@da-gazzi, thank you for submitting this code for review. In general it is a useful change, however we need to review it in details and run the CI tests. Please expect comments in the following days.

**Comment by maychair** [comment]
I have build this pr and get an error:
loader/tt_cluster.cpp: In member function ‘tt_version tt_cluster::get_ethernet_fw_version()’:
loader/tt_cluster.cpp:678:22: error: ‘using element_type = class tt_device’ {aka ‘class tt_device’} has no member named ‘get_ethernet_fw_version’
  678 |     return device -> get_ethernet_fw_version();
Here is my environment: gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0

And the function get_ethernet_fw_version should be a member function of class tt_SiliconDevice and call by point of tt_device. Is this corrent? Or there is some reason i don't realized.

**Comment by vvukomanovicTT** [comment]
Hi @da-gazzi,

Thank you for this useful contribution to our repo! I will review your code and leave comments if needed, but it would be best if you could first rebase your branch onto the newest [branch](https://github.com/tenstorrent/tt-budabackend/tree/bbe_273aecc12fd29ac0fc05730d3ab33d6d2c14d925) snapshot of our repository.

Once you rebase and address comments I will get this merged, as we are still using our internal repository as primary it wont show up as merged until our next mirror but it will be your commits!

*Small heads up, as you probably saw with these changes, our current firmware compiler is not supported on non x86_64 architectures.*

If you have any questions regarding this issue, please feel free to reach out in this thread.

**Comment by staylorTT** [comment]
@da-gazzi have you been able to rebase as suggested in the previous comment?

**Comment by da-gazzi** [comment]
Sorry for being unresponsive - I got sidetracked on other projects. I'm currently away but will do the rebase when I get back next week!

**Comment by da-gazzi** [comment]
So, I did the rebase -- find the corresponding branch here (doing an actual rebase was a nightmare so I went the other way, applying my commits on top of the snapshot branch):
https://github.com/da-gazzi/tt-budabackend/tree/georgr/pr2

Note that the `umd` submodule points to my fork, as there were incompatibilities (`fmt` dependency was restructured in the meantime) between the later versions with fixed compilation and the one the snapshot branch points to. If I can do anything else to make this more useful to you, please let me know!

**Comment by staylorTT** [comment]
Hi @da-gazzi Can you please submit  a PR for your changes on the UMD submodule so we can then rebase with your changes in the official UMD repo? It will be infeasible for us to approve changes that rely on custom UMD changes that are not in the UMD repo.

**Comment by da-gazzi** [comment]
> Hi @da-gazzi Can you please submit a PR for your changes on the UMD submodule so we can then rebase with your changes in the official UMD repo? It will be infeasible for us to approve changes that rely on custom UMD changes that are not in the UMD repo.

Hi,
My PR on the UMD repo was submitted (and accepted) already a while ago :D
The reason for the "custom" changes is that the UMD version used on the branch you pointed me to is old and incompatible with the structure of the UMD repo that has the fixes applied.

As the UMD branch/commit in question is long outdated, I believe the best way to proceed would be for you to manually apply the relevant changes. In any case, it's only 2 lines if I remember correctly. 
Best regards,
Georg

**Comment by vvukomanovicTT** [comment]
Hi @da-gazzi,

Thank you for following up and applying your changes to the snapshot branch! 

Since the last time we spoke, we made a lot of updates in Budabackend which are now synced with GitHub main. 
Unfortunately, some of these changes are in the files you also changed, so we need to merge them. Could you please rebase to the main branch on GitHub? If it is too much trouble I could do that instead and send it to you for review(Of course, you would still be listed as an author and owner of these changes).   

Thank you for contributing,
Vuk

**Comment by staylorTT** [comment]
Hi @da-gazzi, Wanted to confirm if you are OK if we push this change on your behalf? We have it ready to go on our end. Your name will be referenced in the change.

**Comment by vmilosevic** [comment]
Merged with changes from @vvukomanovicTT 
https://github.com/tenstorrent/tt-budabackend/commit/e666db323cf920f68250d8164b3f64530463011c

**Pull request closed without merging**
